#
#   Author: Rohith (gambol99@gmail.com)
#   Date: 2015-03-09 10:46:48 +0000 (Mon, 09 Mar 2015)
#
#  vim:ts=2:sw=2:et
#
- hosts: all
  gather_facts:

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.ntp
    - geerlingguy.git
    - geerlingguy.java
    - packages
    - gocd
